package view;

// Sessão de importação.
import controller.ControllerProjeto;
import controller.ControllerUser;
import java.sql.ResultSet;
import java.sql.SQLException;
import model.Projeto;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import utils.DocumentoLimitado;

/**
 * Classe que define a tela ~ Projeto.
 * @author Vinicius Tavano Ferreira.
 * @since Classe criada em 07/09/2017.
 */
public class ViewSenha extends javax.swing.JFrame {

    private List<Projeto> projetos;
    private Projeto projeto;
    private final User user;

    /**
     * Creates new form FormProjeto
     * @param user
     */
    public ViewSenha(User user) {
        initComponents();
        this.user = user;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        setLocation(350, 200);//(x,y)
        setLocationRelativeTo(null);
//        tfCodigo.setEditable(true);
//        this.atualizarTabela();
//        this.btExcluir.setEnabled(false);
//        this.btLimpar.setEnabled(false);
        tfSenha.setDocument(new DocumentoLimitado(26));
        tfConfirmaSenha.setDocument(new DocumentoLimitado(26));
    }

    private ViewSenha() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelProjeto = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        tfConfirmaSenha = new javax.swing.JTextField();
        tfSenha = new javax.swing.JTextField();
        painelBotoes = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(204, 255, 51));
        setLocation(new java.awt.Point(400, 100));
        setResizable(false);

        painelProjeto.setBackground(new java.awt.Color(255, 255, 255));
        painelProjeto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        lbCodigo.setForeground(new java.awt.Color(0, 153, 255));
        lbCodigo.setText("Nova senha:");

        lbNome.setForeground(new java.awt.Color(0, 153, 255));
        lbNome.setText("Confirmar nova senha:");

        javax.swing.GroupLayout painelProjetoLayout = new javax.swing.GroupLayout(painelProjeto);
        painelProjeto.setLayout(painelProjetoLayout);
        painelProjetoLayout.setHorizontalGroup(
            painelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCodigo)
                    .addComponent(lbNome))
                .addGap(79, 79, 79)
                .addGroup(painelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelProjetoLayout.setVerticalGroup(
            painelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProjetoLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(painelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(painelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelBotoes.setBackground(new java.awt.Color(255, 255, 255));
        painelBotoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(0, 153, 255));
        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("Modificar a senha");
        btSalvar.setName("btSalvar"); // NOI18N
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btMenu.setForeground(new java.awt.Color(0, 153, 255));
        btMenu.setText("Voltar");
        btMenu.setToolTipText("Voltar à tela de menu");
        btMenu.setName("btSalvar"); // NOI18N
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(447, 246));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        this.salvarSenha();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tbProjetoVetoableChange(java.beans.PropertyChangeEvent evt) throws java.beans.PropertyVetoException {
        System.out.println("Printando");
    }

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        //Invoca a tela ~ Cockpit.
        new ViewMenuRecurso(this.user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btMenuActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbNome;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelProjeto;
    private javax.swing.JTextField tfConfirmaSenha;
    private javax.swing.JTextField tfSenha;
    // End of variables declaration//GEN-END:variables

    private void salvarSenha() {
        if (!isCamposValidos()) {
            return;
        }
        
//        Integer codigo = tfCodigo.getText().isEmpty() ? null : Integer.parseInt(tfCodigo.getText());
        String senha = this.tfSenha.getText();
        String codUser = this.user.getCodUser();
//        String etapa = (String) this.cbModeloProcesso.getSelectedItem();

//        if (this.projeto == null) {
//            this.projeto = new Projeto();
//        }
////        this.projeto.setCodigo(codigo);
//        this.projeto.setNome(nome);
//        this.projeto.setEtapa(etapa);

        try {
            ControllerUser.alterarSenha(codUser, senha);
        } catch (SQLException ex) {
            Logger.getLogger(ViewSenha.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.limparCampos();
//        this.atualizarTabela();
    }

    private void removerProjeto() {
//        Integer codProjeto = Integer.parseInt(tfCodigo.getText());
//        try {
//            ControllerProjeto.excluirProjeto(codProjeto);
//        } catch (SQLException ex) {
//            Logger.getLogger(ViewSenha.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(ViewSenha.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        this.limparCampos();
    }
  
    private void limparCampos() {
//        this.tfCodigo.setText("");
//        this.tfNome.setText("");
//        this.cbModeloProcesso.setSelectedIndex(-1);
//
//        this.tfCodigo.setEnabled(true);
//        this.btExcluir.setEnabled(false);
//        this.btLimpar.setEnabled(false);
            this.tfSenha.setText("");
            this.tfConfirmaSenha.setText("");
    }

    private boolean isCamposValidos() {
        boolean isValido = false;

        if (this.tfSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Senha é obrigatório");
        } else if (this.tfConfirmaSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Confirmação de senha é obrigatório");
        } else if (this.tfSenha.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "Senha deve possuir, no mínimo, 6 caracteres");
        } else if (this.tfConfirmaSenha.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "Confirmação de senha deve possuir, no mínimo, 6 caracteres");
        } else if (!this.tfConfirmaSenha.getText().equalsIgnoreCase(
                    this.tfSenha.getText())) {
            JOptionPane.showMessageDialog(this, "Senha e sua confirmação devem possuir o mesmo valor");
        } else {
            isValido = true;
        }
        return isValido;
    }

//    private void atualizarTabela() {
//        String[] colunas = {"Codigo", "Nome", "Modelo proc."};
//        DefaultTableModel tableModel = new DefaultTableModel();
//        tableModel.setColumnIdentifiers(colunas);
//
//        try {
//            this.projetos = ControllerProjeto.lista();
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
//
//        for (Projeto p : this.projetos) {
//            tableModel.addRow(p.getValueAsObject());
//        }
////        this.tbProjeto.setModel(tableModel);
//    }

    private void popularCampos() {

        if (this.projeto != null) {
//            this.tfCodigo.setText(this.projeto.getCodigo().toString());
            this.tfConfirmaSenha.setText(this.projeto.getNome());
//            this.cbModeloProcesso.setSelectedItem(this.projeto.getEtapa());
        }
        
//        this.btExcluir.setEnabled(true);
//        this.btLimpar.setEnabled(true);
//        this.tfCodigo.setEnabled(false);
    }

}//fim do ViewProjeto
